import haxe.Json;
import sys.io.File;
import sys.FileSystem;
import haxe.Http;
import haxe.crypto.Base64;
import haxe.io.Bytes;
import sys.io.File;

using StringTools;

typedef Bookmark = {
	name:String,
	color:String,
	time:Float
}
typedef NoteData = {
	id:Int,
	sLen:Float,
	time:Float,
	type:Int
};
typedef StrumLine = {
	keyCount:Int, // strumline count
	notes:Array<NoteData>, // notes
	position:String, // must equal: girlfriend, boyfriend, or dad.
	strumScale:Float, // scale.
	visible:Bool, // visibilty
	scrollSpeed:Null<Int>, // scrollspeed, self explanitory.
	type:Int, // 2, strum type?? no clue how this works. (2 == additional, 0 == dad, 1 == boyfriend)
	characters:Array<String>, // basically keep empty because it doesnt matter.
	strumPos:Array<Int>, // 0, 50. keep this the same i guess??
	strumLinePos:Float // 0.5 x factor.
};
typedef ChartData = {
	bookmarks:Array<Bookmark>,
	events:Array<Dynamic>, // will always be empty.
	codenameChart:Bool, // always be true
	stage:String,
	chartVersion:String,
	scrollSpeed:Float,
	strumLines:Array<StrumLine>,
	noteTypes:Array<String> // basically keep empty because we wont need it.
};
final class Struct { // ah yes, long strings. i love these (no i dont.)
	public static final version:String = '0.0.5';
	public static final title:String = 'RhythmShift';

	public static final logo:String = '\033[34mChickenSwimmer2020\033[0m
------------------
\033[32m$title v$version\033[0m';

	public static final initMsg:String = "\n\n\033[35mPlease input mod format, song path, and other input varibles.\033[0m\n\033[34mYOU MUST INCLUDE THE DOUBLEQUOTES ON FILEPATH, AND THE PIPES WITH SPACES BETWEEN INPUTS\033[0m\n\n\033[31mDISCLAIMER:\nMULTIKEY SONGS WILL \x1b[3m\x1b[1mONLY\x1b[0m \033[31mWORK WITH CODENAME ENGINE!!!!!!!!!\nUNLESS YOU BUILD A CUSTOM ENGINE FOR FUNKIN OR PSYCH, THEY WILL NOT PARSE CORRECTLY.\033[0m\n\n\033[1;31mSOME SONGS MAY FAIL TO COMPILE PROPERLY. DO NOT CRY AT ME, IM WORKING ON IT.\033[0m\n\x1b[3m\x1b[1mSyntax:\x1b[0m \"\033[32mTYPE\033[0m \033[90m(must be: CODENAME/PSYCH/FUNKIN/KADE)\033[0m || \033[35m\"PATH\"\033[0m || \033[34mCUSTOM_UI\033[0m || \033[34mHITSOUNDS\033[0m\"\n\n";
	public static final helpFile:String = 'how to add FFmpeg to your system PATH\ndownload FFmpeg\ncreate a folder in your C: drive named: "FFmpeg"\nmake a folder in FFMPEG named: "bin"\nmove the installed .exe files into that folder\nopen environment varibles (if you dont know how, run this script in your terminal. "rundll32.exe sysdm.cpl,EditEnvironmentVariables")\ndouble click on the entry labled "Path"\ndouble click on an empty space, then type in "C:\\FFmpeg\\bin"\nclick ok, then click the next ok button\ncongratulations, you have installed FFmpeg into your system PATH!';
	//seperating these into maps might have been my best idea yet!
	public static final cne:Map<String, String> = [
		"modpackIni" => '[Common] # This section applies the "MOD_" prefix to the flags so you don"t have to.\nNAME="{NAME}"\nDESCRIPTION="Auto Generated by {TITLE}"\nAUTHOR="{AUTHOR}"\nVERSION="{VERION}"\n\n# DO NOT EDIT!! this is used to check for version compatibility!\nAPI_VERSION=1\n\nDOWNLOAD_LINK="YOUR MOD PAGE LINK HERE"\n\n# Not supported yet\n;MOD_ICON64="path/to/icon64.png"\n;MOD_ICON32="path/to/icon32.png"\n;MOD_ICON16="path/to/icon16.png"\nICON="path/to/icon.png"\n\n[Flags] # This section doesn"t apply any prefix.\nDISABLE_WARNING_SCREEN=true\n# Set this to false if you want to bring back the warning state (prior to 1.0.0)\n# NOTE: Beta warning state has been renamed from BetaWarningState.hx to WarningState.hx\nDISABLE_LANGUAGES=true\n# Some people might not translate their mods, but if you do then you may set this to false\n[Discord] # This section applies the "MOD_DISCORD_" prefix to the flags so you don\'t have to.\nCLIENT_ID=""\nLOGO_KEY=""\nLOGO_TEXT=""\n\n[StateRedirects]\nFreeplayState="funkin.menus.TitleState"\nMainMenuState="funkin.menus.TitleState"\nStoryMenuState="funkin.menus.TitleState" # This section is used for state redirecting, see examples below.\n[StateRedirects.force] # Use this if you want to override redirects set by subsequent addons/mods',
		"songMeta" => '{"opponentModeAllowed": true,"icon": "face","difficulties": {DIFFICULTIES},"color": "#FFFFFF\","coopAllowed": true,"stepsPerBeat": 4,"displayName": "{TITLE}","needsVoices": false,"beatsPerMeasure": 4,"bpm": {BPM}}',
		"stageHeader" => '<stage name="{NAME}" folder="stages/{NAME}/"><boyfriend/><dad/><sprite name="bg" x="0" y="0" scale="1" sprite="bg" scroll="0"/></stage>',
		"stageScript" => 'function postCreate(){ bg.setGraphicSize(1280, 720); bg.updateHitbox(); }',
		"characterFile" => '<!DOCTYPE codename-engine-character><character color="#000000"/>',
		"settings" => '<menu name="{NAME}" desc=""><number id="hitsoundVolume" name="hitsounds volume" desc="" min="0" max="1" change="0.1"/></menu>',
		"global" => 'function new() if(FlxG.save.data.hitsoundVolume == null) FlxG.save.data.hitsoundVolume = 0.5;',
		"controls" => '<controls><category name="seven key"><control name="7k0" saveName="control_7k0" menuName="LEFT" keyP1="A" keyP2="" menuIcon="game/notes/default" menuAnim="purple0"/><control name="7k1" saveName="control_7k1" menuName="UP" keyP1="S" keyP2="" menuIcon="game/notes/default" menuAnim="blue0"/><control name="7k2" saveName="control_7k2" menuName="RIGHT" keyP1="D" keyP2="" menuIcon="game/notes/default" menuAnim="green0"/><control name="7k3" saveName="control_7k3" menuName="LEFT" keyP1="SPACE" keyP2="" menuIcon="game/notes/default" menuAnim="red0"/><control name="7k4" saveName="control_7k4" menuName="DOWN" keyP1="J" keyP2="" menuIcon="game/notes/default" menuAnim="purple0"/><control name="7k5" saveName="control_7k5" menuName="RIGHT" keyP1="K" keyP2="" menuIcon="game/notes/default" menuAnim="blue0"/><control name="7k6" saveName="control_7k6" menuName="RIGHT" keyP1="L" keyP2="" menuIcon="game/notes/default" menuAnim="green0"/></category></controls>',

		//scripts go down here because they need to be expanded for easy editing.
		"userInterface" => 'function postCreate(){
	healthBar.angle = 90;
	healthBar.updateHitbox();
	var box = add(new FlxSprite(strumLines.members[1].members[0].x + 10, 0).makeGraphic(0+(strumLines.members[1].members[3].width * strumLines.members[1].data.keyCount), 720, 0x7D000000));
	box.scrollFactor.set();
	box.screenCenter();
	healthBar.scrollFactor.set();
	iconP1.visible = iconP2.visible = healthBarBG.visible = false;
	healthBar.x = (box.width);
	healthBar.y -= (healthBar.width/2 - 63);
	scoreTxt.x = scoreTxt.y = accuracyTxt.y = box.y = missesTxt.y = 0;
	scoreTxt.alignment = accuracyTxt.alignment = "left";
	accuracyTxt.x = 780;
		}',
		"hitSoundsScript" => 'function onNoteHit(event) if(event.character == boyfriend && !event.note.isSustainNote) FlxG.sound.play(Paths.sound("hitsound"), FlxG.save.data.hitsoundVolume);',
		"replaceTitleScreen" => 'function new() FlxG.switchState(new ModState("Title"));',
		"titleState" => 'import funkin.menus.ModSwitchMenu;
import funkin.editors.EditorPicker;
import flixel.util.FlxAxes;
var difficulties:Array<String> = [];
var open,goUp:Bool = false;
var hasBanner:String = "{HASBANNER}";
var banner:FlxSprite;

var diffSelector:FlxSprite;
var diffs:Array<FunkinText> = [];
var arrow1:FunkinText;
var arrow2:FunkinText;
var diffSelectorPosition:Float = 0;

var curDifficulty:Int = 0;

var originalBannerScale:Array<Int> = [];
function postCreate(){
	difficulties = [DIFFICULTIES];
	if(FlxG.sound.music != null && FlxG.sound.music.playing) FlxG.sound.music.stop();
	FlxG.sound.playMusic(Paths.inst("{SONG}"));
	FlxG.sound.music.time = FlxG.sound.music.loopTime = {ST};
	Conductor.songPosition = {ST};
	Conductor.changeBPM({BPM});

	var bg:FlxSprite = new FlxSprite(0, 720).loadGraphic(Paths.image("stages/{SONG}/bg"));
	bg.setGraphicSize(1280, 720);
	bg.updateHitbox();
	add(bg);
	FlxTween.tween(bg, {y: 0}, 1.2, {ease: FlxEase.circOut});

	if(hasBanner == "true"){
		banner = new FlxSprite(0, 0).loadGraphic(Paths.image("stages/{SONG}/banner"));
		banner.setGraphicSize(842, 164);
		banner.updateHitbox();
		originalBannerScale.push(banner.scale.x);
		originalBannerScale.push(banner.scale.y);
		add(banner);
		banner.screenCenter();
		var curY:Float = banner.y;
		banner.y = 720;
		FlxTween.tween(banner, {y: curY}, 1.2, {startDelay: 1, ease: FlxEase.circOut});
	}

	diffSelector = new FlxSprite(0, 0).makeGraphic(800, 200, 0xA1000000);
	arrow1 = new FunkinText(0, 0, 0, ">", 24, true);
	arrow2 = new FunkinText(0, 0, 0, "<", 24, true);
	add(diffSelector);
	add(arrow1);
	add(arrow2);
	diffSelector.screenCenter();
	diffSelectorPosition = diffSelector.y;
	diffSelector.y = 720;
	for(i in 0...difficulties.length) {
		diffs.push(new FunkinText(0, diffSelector.y + (20 * i), 0, difficulties[i], 24, true));
		diffs[i].screenCenter(FlxAxes.X);
		add(diffs[i]);
	}
}
var target:Float = 0;
function postUpdate(elapsed:Float) {
	if (controls.DEV_ACCESS) {
		persistentUpdate = false;
		persistentDraw = true;
		openSubState(new EditorPicker());
	}
	
	arrow1.y = FlxMath.lerp(arrow1.y, diffs[curDifficulty].y, Math.exp(-elapsed * 3.125 * 8 * 1));
	arrow1.x = FlxMath.lerp(arrow1.x, diffs[curDifficulty].x - arrow1.frameWidth, Math.exp(-elapsed * 3.125 * 8 * 1));
	arrow2.y = FlxMath.lerp(arrow2.y, diffs[curDifficulty].y, Math.exp(-elapsed * 3.125 * 8 * 1));
	arrow2.x = FlxMath.lerp(arrow2.x, diffs[curDifficulty].x + diffs[curDifficulty].width, Math.exp(-elapsed * 3.125 * 8 * 1));
	FlxG.camera.stopFX();
	FlxG.camera.zoom = FlxMath.lerp(1, FlxG.camera.zoom, Math.exp(-elapsed * 3.125 * 1 * 1));

	for(i in 0...diffs.length) {
		diffs[i].y = FlxMath.lerp(diffSelector.y + (20 * i), diffs[i].y, Math.exp(-elapsed * 3.125 * 8 * 1));
	}

	if(open) {
		if(FlxG.keys.anyJustPressed([87, 38])){
			if(curDifficulty <= 0) curdifficulty = difficulties.length;
			else curDifficulty--;
		}
		if(FlxG.keys.anyJustPressed([83, 40])){
			if(curDifficulty >= difficulties.length) curdifficulty = 0;
			else curDifficulty++;
		}
	}

	diffSelector.y = FlxMath.lerp(target, diffSelector.y, Math.exp(-elapsed * 3.125 * 4 * 1));
	if(goUp) {
		target = diffSelectorPosition;
	}else{
		target = 720;
	}

	if(hasBanner == "true"){
		banner.scale.x = FlxMath.lerp(originalBannerScale[0], banner.scale.x, Math.exp(-elapsed * 3.125 * 2 * 1));
		banner.scale.y = FlxMath.lerp(originalBannerScale[1], banner.scale.y, Math.exp(-elapsed * 3.125 * 2 * 1));
	}

	if ((FlxG.keys.justPressed.ENTER || FlxG.keys.justPressed.SPACE) && !open) {
		goUp = true;
		new FlxTimer().start(0.25, (_)->{open = true;});
	}
	if(open && (FlxG.keys.justPressed.ENTER || FlxG.keys.justPressed.SPACE)){
		PlayState.loadSong("{SONG}", difficulties[curDifficulty], false, false);
		PlayState.isStoryMode = false;
		PlayState.storyPlaylist = ["{SONG}"];
		PlayState.storyWeek = {
			name = "{SONG}";
		}
		FlxG.switchState(new PlayState());
	}
	if((FlxG.keys.justPressed.ESCAPE || FlxG.keys.justPressed.BACK) && open){
		goUp = false;
		open = false;
	}

    if (controls.SWITCHMOD) {
        openSubState(new ModSwitchMenu());
        persistentUpdate = false;
        persistentDraw = true;
    }
}
	
function beatHit(curBeat:Int) {
	if(hasBanner=="true"){
		if(curBeat % 2 == 0){
			FlxG.camera.zoom += 0.02;
		}
	}else{
		if(curBeat % 1 == 0){
			FlxG.camera.zoom += 0.02;
		}
	}

	if(hasBanner == "true" && curBeat % 1 == 0) {
		banner.scale.x += 0.02;
		banner.scale.y += 0.02;
	}
}'
	];
}


class Main {
	static function main() {
		// create the ouput folder on runtime.
		if (!FileSystem.exists('export'))
			FileSystem.createDirectory('export');
		FileSystem.createDirectory('export/mods');
		Sys.print(Struct.logo);
		Sys.sleep(2);
		Sys.print(Struct.initMsg);
		JsonWriter.createChart(Sys.stdin().readLine());
	}
}
class JsonWriter {
	public static var currentPath:String = '';
	public static var generatedInst:Bool = false;
	public static var generatedStage:Bool = false;

	public static var toFile:Array<String> = [];
	public static var toToFile:Array<String> = [];

	public static function createChart(input:String) {
		if (Sys.command("FFmpeg -loglevel quiet -version") == 0) {
			var type:String = input.split(' || ')[0];
			var path:String = input.split(' || ')[1];
			var customUI:String = input.split(' || ')[2];
			var hitsounds:String = input.split(' || ')[3];


			currentPath = path;

			#if debug toFile.push(path.substr(1, path.length - 2)); #end
			if (FileSystem.exists(path.substr(1, path.length - 2))) {
				switch (type.toUpperCase()) {
					case 'CODENAME':
						trace('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ngenerating, this may take a minute...\nplease stand by while we generate the mods file structure...\n'); // simple fix for FFmpeg not shutting the fuck up.
						if(customUI == null || customUI == ''){
							trace('\n    no custom ui value was specified, defaulting to none...\n');
							customUI = 'false';
						}
						if(hitsounds == null || hitsounds == ''){
							trace('\n    hitsounds were not specified. not importing...\n');
							hitsounds = 'false';
						}
						toCodenameMod(path, customUI, hitsounds);
					case 'PSYCH':
						trace('feature not yet implemented, check back in a future version!');
					case 'FUNKIN':
						trace('feature not yet implemented!');
					case 'KADE':
						trace('no.');
					default:
						trace('no type specified! aborting...');
						Sys.exit(0);
				}
			} else
				trace('couldnt find song path!');
		} else {
			trace('\n\n\n\n\n\n\n\nan error has occured, or FFmpeg is not installed.\nif it is the latter, please install FFmpeg from: https://www.FFmpeg.org,\nadd it to your system PATH, then run this program again.\n\n\n\nif you do not know how to add to the system PATH, a guide file has been generated.\n\n\n\n');
			File.saveContent('export/FFmpeg install guide.txt', Struct.helpFile);

	        Sys.println("Press Enter to exit...");
        	Sys.stdin().readLine();
		}
	}

	private static function toCodenameMod(filePath:String, useCustomUI:String, enableHitsounds:String) {
		#if debug toFile.push(filePath); #end
		var files:Array<String> = FileSystem.readDirectory(filePath.substr(1, filePath.length - 2));
		var chartMap:Map<String, String> = [];
		var chartDatas:Array<String> = [];
		for (i in 0...files.length) {
			if (files[i].endsWith('.qua')) {
				#if debug toFile.push('found chart file! ${files[i]}'); #end
				chartDatas.push(File.getContent('${filePath.substr(1, filePath.length - 2)}/${files[i]}'));
			}
		}
		#if debug
		for(i in 0...chartDatas.length){
			toToFile.push(chartDatas[i]);
		}
		#end
		parseChartDataCNE(chartDatas, useCustomUI, enableHitsounds);
	}

	private static function parseChartDataCNE(charts:Array<String>, customUI:String, hitsounds:String) {
		var songDifficulties:Array<String> = [];
		// for charts.
		var header:{
			previewStart:Float,
			audio:String,
			bg:String,
			banner:String,
			mode:Int,
			title:String,
			bpm:Int,
			scrollSpeed:Float,
			difficulty:String,
			creator:String,
			artist:String
		} = {
			previewStart: 0,
			audio: '',
			bg: '',
			banner: '',
			mode: 0,
			title: '',
			bpm: 0,
			scrollSpeed: 3.1, //default value.
			difficulty: '',
			creator: '',
			artist: ''
		};
		var charties:Array<ChartData> = [];
		for (data in charts) {
			var datalines = data.split("\n");

			var bookmarkBlocks:Array<Array<String>> = [];
			var currentBookmarkBlock:Array<String> = [];

			var blocks:Array<Array<String>> = [];
			var currentBlock:Array<String> = [];

			var noteObjects:Array<NoteData> = [];
			var bookmarkObjects:Array<Bookmark> = [];

			var notesStartPointer:Int = -1;
			var possibleNotes:Array<String> = [];

			var possibleBookmarks:Array<String> = [];

			var curLine:Int = 0;
			var foundLine:Bool = false;
			var foundBPM:Bool = false;
			var lookingInBookmarks:Bool = false;
			var ignoreCurrentLine:Bool = false;

			var finishedParsing:Bool = false;

			for (line in datalines) {
				if (curLine == datalines.length - 1) {
					finishedParsing = true;
					#if debug toFile.push('parsed file.\nwriting note data to buffer...'); #end
					for (possibleNote in possibleNotes) {
						if (possibleNote.startsWith('- StartTime:')) {
							if (currentBlock.length > 0)
								blocks.push(currentBlock);
							currentBlock = [];
						}
						currentBlock.push(possibleNote);
					}
					for (mark in possibleBookmarks) {
						if (mark.startsWith('- StartTime:')) {
							if (currentBookmarkBlock.length > 0)
								bookmarkBlocks.push(currentBookmarkBlock);
							currentBookmarkBlock = [];
						}
						currentBookmarkBlock.push(mark);
					}
					break;
				} else {
					curLine++;
					line = line.trim();
					if (line == "") continue;
					// align the header.
					if (line.startsWith('AudioFile')) header.audio = line.replace('AudioFile: ', '');
					else if (line.startsWith('SongPreviewTime')) header.previewStart = Std.parseFloat(line.replace('SongPreviewTime: ', ''));
					else if (line.startsWith('BackgroundFile')) header.bg = line.replace('BackgroundFile: ', '');
					else if (line.startsWith('BannerFile')) header.banner = line.replace('BannerFile: ', '');
					else if (line.startsWith('Mode')) header.mode = Std.parseInt(line.replace('Mode: ', '').replace('Keys', ''));
					else if (line.startsWith('Title')) header.title = line.substr(7, line.length - 1).replace('"', '').replace(',', '').replace('.', ''); // bandaid fix until i make a remove punctuation function.
					else if (line.contains('Bpm') && !ignoreCurrentLine) { // make sure we only read the headers BPM.
						var bpmline:String = line.trim();
						var bpmnum:Array<Int> = [];
						toFile.push(bpmline);
						for (token in 0...bpmline.length) {
							switch (bpmline.charAt(token)) {
								case '0':
									bpmnum.push(0);
								case '1':
									bpmnum.push(1);
								case '2':
									bpmnum.push(2);
								case '3':
									bpmnum.push(3);
								case '4':
									bpmnum.push(4);
								case '5':
									bpmnum.push(5);
								case '6':
									bpmnum.push(6);
								case '7':
									bpmnum.push(7);
								case '8':
									bpmnum.push(8);
								case '9':
									bpmnum.push(9);
								default:
									continue;
							}
						}
						toFile.push(bpmnum.toString().substr(1, bpmnum.toString().length - 2).replace(',', ''));
						header.bpm = Std.parseInt(bpmnum.toString().substr(1, bpmnum.toString().length - 2).replace(',', ''));
					}else if (line.startsWith('InitialScrollVelocity')) header.scrollSpeed = 1 + Std.parseFloat(line.replace('InitialScrollVelocity: ', ''));
					else if (line.startsWith('DifficultyName')) {
						header.difficulty = line.replace('DifficultyName: ', '');
						songDifficulties.push('\"${header.difficulty}\"');
					}else if (line.startsWith('Creator')) header.creator = line.replace('Creator: ', '');
					else if (line.startsWith('Artist')) header.artist = line.replace('Artist: ', '');
					foundBPM = (header.bpm != 0);

					//TODO: FURTHER SUPPORT FOR QUAVER FEATURES.stea
					if(line.contains('Bookmarks:')) lookingInBookmarks = true;
					else if(line.contains('HitObjects:')) {
						lookingInBookmarks = ignoreCurrentLine = false;
						notesStartPointer = curLine;
						foundLine = true;
						#if debug toFile.push('$notesStartPointer start pointer'); #end
					}else if(line.contains('TimingPoints:')){
						lookingInBookmarks = false;
						ignoreCurrentLine = foundBPM;
						//TODO: make these lower ones functional (events? custom events? how am i gonna do this.)
					}else if(line.contains('SliderVelocities:')){
						lookingInBookmarks = false;
						ignoreCurrentLine = true;
					}else if(line.contains('CustomAudioSamples:')) {
						lookingInBookmarks = false;
						ignoreCurrentLine = true;
					}else if(line.contains('SoundEffects:')) {
						lookingInBookmarks = false;
						ignoreCurrentLine = true;
					}
					if(lookingInBookmarks){
						trace(line);
						possibleBookmarks.push(line);
					}
					if (!ignoreCurrentLine && (foundLine && (curLine > notesStartPointer))) {
						possibleNotes.push(line);
						#if debug toToFile.push(line); #end
					}
				}
			}
			#if debug
			toFile.push(header.audio);
			toFile.push(header.bg);
			toFile.push(header.banner);
			toFile.push(Std.string(header.mode));
			toFile.push(header.title);
			toFile.push(Std.string(header.bpm));
			toFile.push(Std.string(header.scrollSpeed));
			toFile.push(header.difficulty);
			toFile.push(header.creator);
			toFile.push(header.artist);
			#end

			if (currentBlock.length > 0)
				blocks.push(currentBlock);

			try {
				for(block in bookmarkBlocks) {
					trace(header.bpm);
					if(block[1] == null) continue;
					bookmarkObjects.push({
						name: block[1].replace('Note: ', ''),
						time: getSongStepFromSongPosition(Std.parseFloat(block[0].replace('-', '').replace('StartTime:', '')), header.bpm),
						color: "#FFFFFF",
					});
				}
				for (block in blocks) {
					var sLen = 0.0;
					var startTime = Std.parseFloat(block[0].trim().replace('-', '').replace('StartTime:', ''));
					var noteID = Std.parseInt(block[1].trim().replace('Lane:', '')) - 1;
					if (block[2].contains('EndTime')) {
						var endTime = Std.parseFloat(block[2].trim().replace('EndTime:', ''));
						sLen = convertQuaverTimeToFunkinTime(startTime, endTime);
					}
					noteObjects.push({
						id: noteID,
						sLen: sLen,
						time: startTime,
						type: 0
					});
					toFile.push('loading blocks');
					for(i in 0...block.length) toFile.push(block[i]);
				}
			} catch (e:Dynamic) {
				toFile.push(e);
			}

			// noteObjects.toString().replace('},', '},\n').substr(1, noteObjects.toString().replace('},', '},\n').length - 2)
			var chart:ChartData;
			chart = {
				bookmarks: bookmarkObjects,
				events: [],
				codenameChart: true,
				stage: header.title.substr(0, header.title.length),
				chartVersion: "1.0.6",
				scrollSpeed: header.scrollSpeed,
				strumLines: [
					{
						keyCount: 0,
						notes: [], // notes
						position: 'dad', // must equal: girlfriend, boyfriend, or dad.
						strumScale: 0, // scale.
						visible: false, // visibilty
						scrollSpeed: null, // scrollspeed, self explanitory.
						type: 0, // 2, strum type?? no clue how this works. (2 == additional, 0 == dad, 1 == boyfriend)
						characters: ['empty'], // basically keep empty because it doesnt matter.
						strumPos: [0, 0], // 0, 50. keep this the same i guess??
						strumLinePos: 0 // 0.5 x factor.
					},
					{
						keyCount: header.mode,
						notes: noteObjects, // notes
						position: 'boyfriend', // must equal: girlfriend, boyfriend, or dad.
						strumScale: 1, // scale.
						visible: true, // visibilty
						scrollSpeed: null, // scrollspeed, self explanitory.
						type: 1, // 2, strum type?? no clue how this works. (2 == additional, 0 == dad, 1 == boyfriend)
						characters: ['bf'], // basically keep empty because it doesnt matter.
						strumPos: [0, 50], // 0, 50. keep this the same i guess??
						strumLinePos: 0.5 // 0.5 x factor.
					}
				],
				noteTypes: []
			};
			trace(bookmarkBlocks);
			charties.push(chart);
		}
		writeMod('codename', songDifficulties, header, charties, customUI, hitsounds);
	}


	private static function writeMod(type:String, difficulties:Array<String>, header:{
		previewStart:Float,
		audio:String,
		bg:String,
		banner:String,
		mode:Int,
		title:String,
		bpm:Int,
		scrollSpeed:Float,
		difficulty:String,
		creator:String,
		artist:String
	}, charts:Array<ChartData>, useCustomUI:String, enableHitsounds:String) {
		var weHazBanner:Bool = false;
		// generate the file structure system we need.
		FileSystem.createDirectory('export/mods/${header.title}/data');
		FileSystem.createDirectory('export/mods/${header.title}/data/characters');
		FileSystem.createDirectory('export/mods/${header.title}/data/stages');
		FileSystem.createDirectory('export/mods/${header.title}/data/states');
		FileSystem.createDirectory('export/mods/${header.title}/data/config');
		File.saveContent('export/mods/${header.title}/data/config/modpack.ini',
			Struct.cne.get('modpackIni').replace('{NAME}', header.title)
				.replace('{TITLE}', Struct.title)
				.replace('{AUTHOR}', header.artist)
				.replace('{VERION}', Struct.version));
		FileSystem.createDirectory('export/mods/${header.title}/images');
		FileSystem.createDirectory('export/mods/${header.title}/images/stages');
		FileSystem.createDirectory('export/mods/${header.title}/images/stages/${header.title}');
		FileSystem.createDirectory('export/mods/${header.title}/songs');
		// create song point
		FileSystem.createDirectory('export/mods/${header.title}/songs/${header.title}/charts');
		FileSystem.createDirectory('export/mods/${header.title}/songs/${header.title}/scripts');
		FileSystem.createDirectory('export/mods/${header.title}/songs/${header.title}/song'); // inst goes here.
		generatedInst = FileSystem.exists('export/mods/${header.title}/songs/${header.title}/song/inst.ogg');
		if(header.mode == 7){
			File.saveContent('export/mods/${header.title}/data/config/controls.xml', Struct.cne.get('controls'));
		}
		if(!generatedInst) generateInstFile(header.audio, header.title);
		if(!generatedStage) weHazBanner = generateStageFile(header.bg, header.banner, header.title);
		if(useCustomUI == 'true') File.saveContent('export/mods/${header.title}/songs/ui.hx', Struct.cne.get('userInterface'));
		if(enableHitsounds == 'true'){
			FileSystem.createDirectory('export/mods/${header.title}/sounds');
			FileSystem.createDirectory('export/mods/${header.title}/data/config');
			EmbeddedSound.writeSoundToFile('export/mods/${header.title}/sounds/hitsound.ogg');
			File.saveContent('export/mods/${header.title}/songs/hitsounds.hx', Struct.cne.get('hitSoundsScript'));
			File.saveContent('export/mods/${header.title}/data/global.hx', Struct.cne.get('global'));
			File.saveContent('export/mods/${header.title}/data/config/options.xml', Struct.cne.get('settings').replace('{NAME}', header.title));
		}
		File.saveContent('export/mods/${header.title}/data/characters/empty.xml', Struct.cne.get('characterFile'));
		File.saveContent('export/mods/${header.title}/songs/${header.title}/meta.json', Struct.cne.get('songMeta').replace('{TITLE}', header.title).replace('{DIFFICULTIES}', difficulties.toString()).replace('{BPM}', Std.string(header.bpm)));
		for (i in 0...charts.length) {
			File.saveContent('export/mods/${header.title}/songs/${header.title}/charts/${difficulties[i].replace('"', '')}.json',
				Json.stringify(charts[i], null, '	'));
		}

		#if debug
		toFile.push(header.difficulty);
		for(i in 0...toToFile.length){
			toFile.push(toToFile[i]);
		}
		File.saveContent('export/mods/DEBUGOUTPUT (${header.title.toUpperCase()}).log',
			toFile.toString().replace(',', ',\n')); // save to the log but only if debug
		#end

		File.saveContent('export/mods/${header.title}/data/states/Title.hx', Struct.cne.get('titleState').replace('{HASBANNER}', weHazBanner?'true':'false').replace('{SONG}', header.title).replace('{BPM}', Std.string(header.bpm)).replace('[DIFFICULTIES]', difficulties.toString()).replace('{ST}', Std.string(header.previewStart)));
		
		File.saveContent('export/mods/${header.title}/data/states/TitleState.hx', Struct.cne.get('replaceTitleScreen'));

        Sys.println('\n\n\n\n\n\n\n\n\n\n\n\nMod: (${header.title}) exported ${header.bpm == 0?'with problems...':'successfully!'}');
		if(header.bpm == 0) Sys.println('WARNING: bpm not specified in song file! chart will not be playable!\nplease modify "${header.title}/songs/meta.json" and specify a bpm!');
		Sys.println('\nPress Enter to exit...');
    	Sys.stdin().readLine();
	}

	private static function generateInstFile(name:String, title:String) {
		#if debug toFile.push('$currentPath/${name}'); #end
		trace('generating inst file, this might take a while depending on the power of your machine...');
		if (Sys.command('ffmpeg -i ${currentPath.substr(0, currentPath.length - 1)}/${name}" -map_metadata -1 -map 0:a -loglevel quiet -c:a libvorbis -q:a 4 "export/mods/$title/songs/$title/song/inst.ogg"') == 0) {
			trace('Successfully generated inst file!');
			#if debug toFile.push('made inst file correctly.'); #end
			generatedInst = true;
		} else {
			trace('Couldnt generate inst file!');
		}
	}

	private static function generateStageFile(image:String, banner:String, title:String):Bool {
		var weHazBanner:Bool = false;
		#if debug toFile.push('$currentPath/${image}'); #end
		#if debug if(banner != '') toFile.push('$currentPath/${banner}'); #end
		
		// pull images from the quaver folder
		File.saveBytes('export/mods/$title/images/stages/$title/bg.png', File.getBytes('${currentPath.substr(1, currentPath.length - 2)}\\${image}'));
		if(banner != ''){
			weHazBanner = true;
			File.saveBytes('export/mods/$title/images/stages/$title/banner.png', File.getBytes('${currentPath.substr(1, currentPath.length - 2)}\\${banner}'));
		}

		// generate the stage files themselves
		File.saveContent('export/mods/$title/data/stages/$title.xml', Struct.cne.get('stageHeader').replace('{NAME}', title));
		File.saveContent('export/mods/$title/data/stages/$title.hx', Struct.cne.get('stageScript'));
		generatedStage = true;
		return weHazBanner;
	}

	// SOLAR YOUR A GODSEND!!!!!!!!!!!!! :pray:
	private static function convertQuaverTimeToFunkinTime(start:Float, end:Float):Float {
		return end - start;
	}
	private static function getSongStepFromSongPosition(time:Float, bpm:Int):Float {
        var msPerBeat:Float = 60000.0 / bpm;
        var msPerStep:Float = msPerBeat / 4;
        return Std.int(time / msPerStep);
	}
}
class EmbeddedSound {
	//dont touch this, this is the hitsound.
    static inline var base64Data = "T2dnUwACAAAAAAAAAAAuNQAAAAAAABIsBI4BHgF2b3JiaXMAAAAAAkSsAAAAAAAAbaAHAAAAAAC4AU9nZ1MAAAAAAAAAAAAALjUAAAEAAADkmETeETv///////////////////9TA3ZvcmJpcysAAABYaXBoLk9yZyBsaWJWb3JiaXMgSSAyMDEyMDIwMyAoT21uaXByZXNlbnQpAAAAAAEFdm9yYmlzK0JDVgEACAAAADFMIMWA0JBVAAAQAABgJCkOk2ZJKaWUoSh5mJRISSmllMUwiZiUicUYY4wxxhhjjDHGGGOMIDRkFQAABACAKAmOo+ZJas45ZxgnjnKgOWlOOKcgB4pR4DkJwvUmY26mtKZrbs4pJQgNWQUAAAIAQEghhRRSSCGFFGKIIYYYYoghhxxyyCGnnHIKKqigggoyyCCDTDLppJNOOumoo4466ii00EILLbTSSkwx1VZjrr0GXXxzzjnnnHPOOeecc84JQkNWAQAgAAAEQgYZZBBCCCGFFFKIKaaYcgoyyIDQkFUAACAAgAAAAABHkRRJsRTLsRzN0SRP8ixREzXRM0VTVE1VVVVVdV1XdmXXdnXXdn1ZmIVbuH1ZuIVb2IVd94VhGIZhGIZhGIZh+H3f933f930gNGQVACABAKAjOZbjKaIiGqLiOaIDhIasAgBkAAAEACAJkiIpkqNJpmZqrmmbtmirtm3LsizLsgyEhqwCAAABAAQAAAAAAKBpmqZpmqZpmqZpmqZpmqZpmqZpmmZZlmVZlmVZlmVZlmVZlmVZlmVZlmVZlmVZlmVZlmVZlmVZlmVZQGjIKgBAAgBAx3Ecx3EkRVIkx3IsBwgNWQUAyAAACABAUizFcjRHczTHczzHczxHdETJlEzN9EwPCA1ZBQAAAgAIAAAAAABAMRzFcRzJ0SRPUi3TcjVXcz3Xc03XdV1XVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVYHQkFUAAAQAACGdZpZqgAgzkGEgNGQVAIAAAAAYoQhDDAgNWQUAAAQAAIih5CCa0JrzzTkOmuWgqRSb08GJVJsnuamYm3POOeecbM4Z45xzzinKmcWgmdCac85JDJqloJnQmnPOeRKbB62p0ppzzhnnnA7GGWGcc85p0poHqdlYm3POWdCa5qi5FJtzzomUmye1uVSbc84555xzzjnnnHPOqV6czsE54Zxzzonam2u5CV2cc875ZJzuzQnhnHPOOeecc84555xzzglCQ1YBAEAAAARh2BjGnYIgfY4GYhQhpiGTHnSPDpOgMcgppB6NjkZKqYNQUhknpXSC0JBVAAAgAACEEFJIIYUUUkghhRRSSCGGGGKIIaeccgoqqKSSiirKKLPMMssss8wyy6zDzjrrsMMQQwwxtNJKLDXVVmONteaec645SGultdZaK6WUUkoppSA0ZBUAAAIAQCBkkEEGGYUUUkghhphyyimnoIIKCA1ZBQAAAgAIAAAA8CTPER3RER3RER3RER3RER3P8RxREiVREiXRMi1TMz1VVFVXdm1Zl3Xbt4Vd2HXf133f141fF4ZlWZZlWZZlWZZlWZZlWZZlCUJDVgEAIAAAAEIIIYQUUkghhZRijDHHnINOQgmB0JBVAAAgAIAAAAAAR3EUx5EcyZEkS7IkTdIszfI0T/M00RNFUTRNUxVd0RV10xZlUzZd0zVl01Vl1XZl2bZlW7d9WbZ93/d93/d93/d93/d939d1IDRkFQAgAQCgIzmSIimSIjmO40iSBISGrAIAZAAABACgKI7iOI4jSZIkWZImeZZniZqpmZ7pqaIKhIasAgAAAQAEAAAAAACgaIqnmIqniIrniI4oiZZpiZqquaJsyq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7ruq7rukBoyCoAQAIAQEdyJEdyJEVSJEVyJAcIDVkFAMgAAAgAwDEcQ1Ikx7IsTfM0T/M00RM90TM9VXRFFwgNWQUAAAIACAAAAAAAwJAMS7EczdEkUVIt1VI11VItVVQ9VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV1TRN0zSB0JCVAAAZAACExQehjFISk9Ra7MFYijEIpQblMYUUg5aEx5hCylFOomMKIeUwp9I5hoyR2mIKmTJCWfE9dowhhz0YnULoJAZCQ1YEAFEAAAZJIkkkyfI8okf0LM/jiTwRgOR5NI3nSZ5H83geAEn0eB5NkzyR59E0AQAAAQ4AAAEWQqEhKwKAOAEAiyR5HknyPJLkeTRNFCGKlqaJHs8TRZ4mikTTNKGalqZ5Is8TRZonikxRNWGanuiZJtN0VaapqlxZliG7nieaJtNUXaapqmRXliHLAAAALE8zTZpmijTNNImiacI0Lc0zTZommjTNNImiacI0PVFUVaapqkxTVbmu68J1PdFUVaKpqkxTVbmu68J1AQAASJ5mmjTNNGmaKRJF04RpWppnmjTNNGmaaBJF04RpeqboqkzTVZmiqlJd14XreqKpukxTVYmmqnJV14XrAgAA0EzRdYmiqxJFVWWargrV1UTTdYmi6hJFVWWaqgtVFVVTdpmm6zJN16WqrgvZFU3VlZmm6zJN16W6rgtXBgAAAAAAAAAAgKiassw0XZdpui7VdV24rmiqssw0XZdpui5XlV24rgAAgAEHAIAAE8pAoSErAYAoAACL40iSZXkex5EkS/M8jiNJmuZ5JMmyNE0UYVmaJorQNM8TRWia54kiAAACAAAKHAAAAmzQlFgcoNCQlQBASACAxXEkybI0zfNE0TRNk+RIkqZ5nueJommqKkmyLE3zPM8TRdNUVZZkWZrmeaJomqqqurAsTfM8UTRNVXVdaJqmiaIomqaqui40TfNEURRNU1VdF5rmeaJomqrqurIMPE8UTVNVXdd1AQAAAAAAAAAAAAAAAAAAAAAEAAAcOAAABBhBJxlVFmGjCRcegEJDVgQAUQAAgDGIMcWYYQpKKSU0ikEpJZQIQkippJRJSC211jIoKbXWWiWltFZayqSk1lJrmZTUWmutAACwAwcAsAMLodCQlQBAHgAAg5BSjDHGGEVIKcYYc44ipBRjjDlHEVKKMeeco5QqxRhzzlFKlWKMOecopUoxxphzlFLGGGPMOUqplIwx5hyllFLGGGOMUkopY4wxJgAAqMABACDARpHNCUaCCg1ZCQCkAgA4HMeyNE3TPE8UJcexLM8TRVE0TctxLMvzRFEUTZNlaZrniaJpqirL0jTPE0XTVFWm6XmiaJqq6rpU1fNE0TRV1XUBAAAAAAAAAAAAAQDgCQ4AQAU2rI5wUjQWWGjISgAgAwCAMQYhZAxCyBiEEEIIIYQQEgAAMOAAABBgQhkoNGQlAJAKAEAYoxRjzklJqTJGKecglNJaZZBSzkEopbVmKaWcg5JSa81SSjknJaXWmikZg1BKSq01lTIGoZSUWmvOiRBCSq3F2JwTIYSUWouxOSdjKSm1GGNzTsZSUmoxxuacU661FmPNSSmlXGstxloLAEBocAAAO7BhdYSTorHAQkNWAgB5AACQUkoxxhhjTCmlGGOMMaaUUowxxphTSinGGGPMOacUY4wx5pxjjDHGGHPOMcYYY4w55xhjjDHGnHPOMcYYY8455xhjjDHnnHOMMcaYAACgAgcAgAAbRTYnGAkqNGQlABAOAAAYw5RzzkEoJZUKIcYgdFBKSq1VCDEGIYRSUmotas45CCGUklJr0XPOQQihlJRai6qFUEopJaXWWnQtdFJKSam1GKOUIoSQUkqttRidEyGEklJqLcbmnIylpNRajDE252QsJaXWYoyxOeeca621FmOtzTnnXGspthhrbc45p3tsMdZYa3POOZ9bi63GWgsAMHlwAIBKsHGGlaSzwtHgQkNWAgC5AQCMUowx5pxzzjnnnHPOSaUYc845CCGEEEIIIZRKMeaccxBCCCGEEEIoGXPOOQchhBBCCCGEUErpnHMQQgghhBBCCKGU0jnnIIQQQgghhBBCKaVzzkEIIYQQQgghhFJKCCGEEEIIIYQQQgillFJCCCGEEEIIIYQQSimlhBBCCCGEEEIIIZRSSgkhhBBCCCGEEEIopZQSQgghhBBCCCWEUEoppZQQQgihhBBCCKGUUkopIYRSSikhhBBCKaWUUkIooYQQQgghlFJKKaWUEkIpIYQQQgillFJKKaWUUkIIIYQQSimllFJKKaWEUEIIIZRSSimllFJCKCWEEkIopZRSSimlhFBCCCGEUEoppZRSSgkhhBJCCKEAAKADBwCAACMqLcROM648AkcUMkxAhYasBADSAgAAQ6y11lprrbXWWmsNUtZaa6211lprrbVGKWuttdZaa6211lprqbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaSymllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSAdgFGw6A0RNGElJnGVYaceMJGCKQQkNWAgBpAQCAMYwx5hh0EEpJKaUKIecghE5CKq3FFmOEkHMQQiglpdZiizF4DkIIIZTSUmwxxlg8ByGEEFJqLcYYYwyyhVBKKSm11mKMtRbZQiillJRaizHWWoMxppSSUmqt1VhjrMUYE0pIqbXWYsy11mJ8rCWl1GKMscZYazHGthRSiS3GWGuNtRhhjGqtxVhjrbHWWowxwpUWYoq11lpzLUYIY3OLMdZYa665FmGM0bmVWmqNsdZaiy/GGGFrrDXGWmvOxRgjhLC1thprzTXXYowxxggfY6y11txzMcYYY4SQMcYaa865AIDcCAcAxAUjCamzDCuNuPEEDBFIoSGrAIAYAIAhAIRisgEAgAkOAAABVrArs7Rqo7ipk7zog8AndMRmZMilVMzkRNAjNdRiJdihFdzgBWChISsBADIAAMRZzTnHnCvkpLXYaiwVUg5SijF2yCDlJMVaMmQQg9Ri6hQyiEFqqXQMGQQlxlQ6hQyDXGMroWMOWquxpRI6CAAAgCAAwECEzAQCBVBgIAMADhASpACAwgJDx3AREJBLyCgwKBwTzkmnDQBAECIzRCJiMUhMqAaKiukAYHGBIR8AMjQ20i4uoMsAF3Rx14EQghCEIBYHUEACDk644Yk3POEGJ+gUlToQAAAAAAAIAHgAAEg2gIhoZuY4Ojw+QEJERkhKTE5QUlQEAAAAAAAQAD4AAJIVICKamTmODo8PkBCREZISkxOUFJUAAEAAAQAAAAAQQAACAgIAAAAAAAEAAAACAk9nZ1MAAMALAAAAAAAALjUAAAIAAABBqewfF/r+8PHi597fycfUwv//////L//////PFCLLNWd31R1MKg3ONHgsydj1qmhBAQRknZ68fj/+B48DoPevnvSbdnvbB4v9tNmoPuwvXjx58mQ41NTK/mp0Op3aevHl/fnx+ZPrtd569trrfdp37ovrvn/5ZlbrZr/89Ns/fzkQ0/vSynSceoTILM97Y4/PHaS7hYG5h5/ZWwOzQ4+wnxQ/5Tljj5Frj5wqhuUBpK0OawGC/a/5wq5WeRmko2+ufXg4+mXp7px49qtwE4/x0YYRax3MPl/K89FWReA1L+1+a6wjZYowRc1r3J1acadvyTfjV5uyeT0cKrzUx3LHghzsD9X/9SszOV2brv9Ox/nbj0z7GfQldw61GbNUc9oJsjvkFUUOpLsFSbFOv794fNbeOE+ALZumddT36jM8f9oYtWg0Ri8cuPrZ90fzPN7t4x4vL/Pav+9dz+eb2unriT/8VcdPnxx/m8+ktG79/PTteLhjjmsMv3g+25tzvB4d2lml7lVE++LopIm14iTRlAHWr5zR5BioVZ9fzrfI1/zTpu8j5NMj7/VOSUeev+64lXfNXbaOXOPmmVcI2C9K+n7mo8KrsoaVw7S2aRGwUH/ALFTwFmbx2MB/vj5OOUroVpz/82zLen4r3DLP8d79cJE0QGqhxR5fqXH0tLl/C4lSO0GOKrPj81duz9xM5Jr4/n4CzBWv6cCYb4av9pK7u4J0dhXCap0BADZX2/KvsZsXff3bw93YvPR+e7Q9/nC83OOf0d8e2u+swjq9u7H/x396T/oY83nPdpc/LO6+68h9/va5br+XZ6erz6f+fDsflfdMeWQsX5zbZYbFLW7O9kLOeSbz+j5bL/nwKSVyT1zJZiSVcDzDE7kUCWK/+tuV7wOTvVDob9gbUgN/as84dyVJ6y9Xn3gPmHIRPjLbhDmQc2lKm0hcnek9zx+aFY2TcLMYrUbec4iA8+WrG7FORAd+P3j+Xv9+u612u+lbmfp9O28eplu9h+//b2TlXhprtzkDpBmvfdafGXEuyuoQWVaJIizTjeRwGx+99/jJ61PXt+2vXi8+6f/li8ah9drv/1Fe2OL88+Hjv/J9uRXj4/rRZaS8Ze7vv515f+Yd//ll7QmZjtt/Mh+L/Cbzz2fr8KN+/fXp2Npe/Lfd1yW3NQpvmWBZU/cjRLj4OHA4cID1ojNPBZyx9yQrTe4QtuZKC2qGpauRsYYb05gTMxJ5+p55s83M2fO38dcrlmzoNh2HOjrtFL2gP/ps3l0Fl2F6RT3uqfnH58mCn0GtMosQ69Q1tpDlVYRpDX67cqv1vuYHwYCsysMxIfzLCaD/wVt+0mq3AMwNr/lFDH6eol3mzXj9wDDV2vkJ1rjMLtfKfR0/rcfvf9X+ZI+9P758fdNv/+trY/3VG83+2PfocX72+zSYctv+6188OXXKn+Sy2ps3r9/y3CyzzoUp3vRy9dCMh+vZf761jj/u++RyOmOP/cUnClKr9ndfHj/w9qGnDD7677Q3t0eaLz1jnzM3QjV7r6Oxh5xg6EUTBuliW7X/UeGgaT+qB1cSJRoi95PW3bMOhPiAFFvczL1v71k7O06siC7nof3GWNhr50HfJffWFw8NwX+r38/z7CdztG/v5m77V1ZaaQn0Hct/WEl818HWtc077h76SEjvZ4yaaa3T+e3VMfM8nQB62321L7f7I/+qrcPrWW+Pf0zEcT9XPv3hlv08Z7mfz37ZV9txz/dNRci3+tPXka+vPu5V9Ijpt64Pr6/fpmU3Pa9xJ+6XTfKoVShwxg6n5P/ldh8/u37U93wy/qy2rFY2wV2Eq8nq+pyOoM4W8cGtrue/yq0tRvxNTzYUbrhVIzqAmK6/7dDhxL+njbogg3nqHLNkv34/tUudqQf8u2Z4SYE5fXi48rWJLEutzgPg2W7z9Xq9rKZ0E03x97nau93wg7/vDgP0Gcv/MQf9cmE73N9x55BHYu34G4yNvhwYf/tojsjB9yOy78GFf99M/Y3BV/x/PD4/f0zXH1o+9iU3Mm7Xf/1fbskfl805iMq5m6HF25iv949zyz9+Kb66/OXS8Txl/fTtKGeGWrlrTZIkcMggAQm+9TXBOZ8X7Z0XWpW5ueHPuTLWBNeuPX5Ln//Weo/M5v/MD7q0SzccqYpuUi7QvcB0x/HWpESTeLlxR52qJoAIzxWTmC2nPPJqi/8KYepiTxq+0+7FqGXZBMmz2NW/2oCEAGDtRxvWbe7j1DF8Mw78BUt+mRiv/+FWfcJdM0/qnw6gsY/4Ps+nXuzuF/NfxP6LN75PH3zt15f8+ZG/8ivv38f/0cvXW5lfbt953Lot/Pj019SPL4+f8vhy25h+f+xD3dX/UDnm4HXPTxm6Oyq1KOe3Q8U6ORoZ5CGJDD7+ZeOdB1IJqlpDnvtOCwRM2m1M23NiwbCrW9UUqv2fn/2fQnsipR841VfOv35TFXDNxwNZoD6eNVScHZ9zDkqM/z+1847qD6DiV8Z+xvzr4zuPuXl987cOD/HGduMxFn0LOP4mRj99O40Y3t92MzcH3BF3/7LS/WKhJtOWr/ykiX8+JZy78fj0+/j9iVdP1s8/X8+Gf+irn32ew9Ufz/7Ur/7zb//j9dkNx/Uhzk29umZUjvUkvHo8dwQvx6dDLc863bMftZBDzpqvT6fH3C8vj494PixyAP1nW1FfoYVLyzV7XYw2ap23CfouXMVKPtXdQ9q9m7zS6Cl7X4rgg398v3lbUoX+9K3urdiKBDAgrccqf2S4NlJ6ATLSa0dwv4Q4Aqj8W0CHTUDMVrkfrt7uHStOP2j/Qy4AnCFf89tV+nd+sGlTXv+TLXrvSzis9QCnL8MsvJaPaIyHj7a+bvnov253PtW+np3nrUXqzlLjdu5Tc43pUMqinMn9bYbVXcttipAZI+u4laVzm0kOxYPPJ/LxAePs/oQVSjb0szcbJ93duv/k+I85Hpv8yXZqJ/7v1DpB+3ZJ6ljV3IHVu8AedhHq/NeG4L8XqdLXgMbxvSmgYrZo5FDMHYePq4vYJB6zr7caC41qy+PVP7Nd5RvUtoyS9DWY5Haqbsl3pclRxmz9Xv0jpT6VuB2uO+bVF26ziwX32djfP3n5ZuSL+uZ8/nfPjs5+a2x9v7+Z3zvrfX2Zrd533Z8+eXe92/GbbLDImtOh67Vcn3O551pfStML91l2md7xqX/fvPWbjpnjy3rbuR/73vrPRdn/1yk3WqxBhwtt7fjp7cSZtPev8XiBY5OnnsyThzi+c8Y9rLLyycxkcCl+vHz2ArfrV8DFql9PmWHl00HNPFOYWJWQxfbCKcL2LTUCQV79Pi9TINftg9cCDPFd1JvyttmGmcPxq1hyPxcAzBGv/OWmPuviXQYid3zrQ9zPgUVj9J9uxw9nrTC8/frh/HbEfPnw3XtYv6ZfeT4G/Prnt/YebPqpFhyJGk7oAcfZcdaW1+JdWiWwb7RzWlJKXyxfTh+f67X/kEAmJVHLj1xoAKia4amj9/hnCnpurfaJ8zS10SI/L3ZufXHszu1+Uutz5+b0z09IaabOLhdqO/zTgXfIXvM9E4Jw2avGOCSeMRBc9sc6a9cK8K1uUFLkEM6Xh6KKvP2UpGfgKCBbX1LapNs05L9hL8AEroyblvuzx/8B+wnSm7DHD+7Wnt09mb9w/vsvv02v918Mzj9+tjy68uz8evdqcP7h7rjNHp+eevzy9fuajerL50e0m19UnX/Sv/6619hYXn8y5nTr6yf/69aPy+f4PHFub7pxuevN3T3nP+bnfnb322rN3r+dXuyvL87N330+/PD4VF9n9LWtlqvbX/bwJ1/X14bhvdPdXam8uaWtfo9z43//4//7f5su7mb/pLtD61z/Xfjj/XP88c4fk3x6vEsR94mP3LifPz//tufNHzvtR17bb+/c2r7rf/2g+pxy1DzMoA3heG7k8nI9/++6Tko4vZzed5/9uOqfuc7sKZZ1SZX6bcxLR1/71TXPTmpDcVBWamroFw1Fc1H0dTYp1FpWR49d6nU+74/9ou407nZXcLiohOhZXxdwPRKpf4MiSD1koI8suRoI2F+rSB8nUdC1d+3Yr5TXPTNU6X5XG2Rtasj+HXKdhEo0ulAlH4mabiccK7iide0lm/mg6AxeujKdV6nMXXcl9jhTXsejgO5jeg1BtIe9jMuYUio1HzGFtnvPQd4/Bw3r6Xh0aKWeLa1FKMH0qvXjgOnhIKuZQW1krjjU2hw1Ml50JgCng8A5qHMNM0vNyD7g52GYokZLsdfK1EJD6AziRNR4ig44qNDgFCip9EGtEMIHR9TqJOzUDs1Loymc2pDAQE8+kximm6Ea2B8eP4PSCYBSCiDCvqNqHrtVkMPmEnaYdrWQtdXd7iVQ33fJerh1K07+u/f+ibrTA6z1Qzxy2fiuSaMl/3zZrNzME4PFgTBf2nTmi93/38HOm/8cBi+sahrvybSimWtUMHD5dfeqsqtXOdUFcXh792Z++IG1VbS0OPiJ64r8+m387ZrpPdGxTts9dmx29C0x4mygqTbvgz3aJ1Hy35xWNhpmej6+tB9Ur5mRjHvRh1ffqji+vmJVTve2lvbukf3TqYI+sqdGNqnHrrTHulbnbcy/GHwHkqcHqX9PdbECJej/4iLrnskAfzVsM2Ji+3li40HZKeyyp6drgQwrRGJyhu6J42wYZ9OF/LbStH7Y1UCDrx4Ug/eNKuK8yy6L73Klwm/OoKLMJI2a1Ke8hiyYb34LbJU7OyiuIr8b87CYuEEncBc6z/mr6I0a5HTF5Zj52s3LwGhjMAJc1b9QPz+kfhviv9otWHnf9S16geNJ2QjdglysfPs/c7beEb61VSTpUb62fkvx3m6RsXVdJvovS7d9VSfu+rPid9puC877Y/w3dR34ir3V3ObwQb/0OxoZTK1ijFci+/+HMIwWMA8THPhXzn8vyh0/QPj7+8d+I+C/ka0jrvp88jeKpBS77hIo/+nMczx84/OxB3z3c2E96Dk+yHBVXeiVOzufI1PNoCeaPO7zBBsD8uT5EN7sL4pfuYPMlrq53kbW7uk9+kSNeE7GcNkhUDvct/fRNZ9IsbWb6PSeZq9bSebo5CforlWb9QRiiCApcDZeYT2qQ7Xu/q1Iy7yZNPhR8KtoIPHbbyNh1Y3b2xmCOKMhBf9l92oeOihL2PlSLIkfsejslpsT/dHHfzniGDzB9gtdjyp5i7jx8XkSOcgutHIVJ6zuonwC6sLZOywUTu1+K4vuapNwmJpMvKEeOa1dn4oVbuyKPNUN6+Du/uebI123Q/j5O3h+6rwO4Jcsgn0F3NW+04Rh/iKxOJbh960L7J/zWmdMy3zfvhqruzP3t2431GfuQqPuLn/0rpfa1KfXT3wf3rV8AP502/Tg/848AQRcpoCbOfh/x88EBRshFmF/4/wcZ9xj6FHCvaajnkMzbcxCDN8apOuhIfEIXlLfr0Tlmpq1avw3md8ToavMA0k9KtnPU6SoXtDvj8dZzx/Xs/f596v3YjhOZXUk5lu/x5q6PzQCqCj1LKqbqZ2OuiAL2l9B6ul0rn8w75rTdbpzV2qT3ZHxoTyy6Z+SQnd9Ko+seVej9++UVz/UJuM8JDQV1ut0omm8qC15faNVJuouKjpF7enxH6lx9QXCLC8Zepwg9UTJqF1PHBoqQH2EbDmrwKSVVRJ6rV3ny13jzK90fEuZPeM9v19XLWTKIljg6ELQ9zrOqtRZAj3JQGpPkYErcwzx2kFcgeRETSk6aAk5dMlFW/lInOpUwkG6LyapSY1KBjuRX7UPR2fdnYasMwGnikilVkfyoch6KFkrHdRKIXWCWudwaE63EkfH2VULZv7dy1Iftg8ZbRaZk1RRiBpzA6Aq8nv1tJi//ZzV6f28yPNY8vzN5zbizLWhKwdBlVcnuyVDJepBUzs5zNogoYEO0YEeQ56zEHrr8fj4elDdHtk8pz7iBFQ9MpyiUuOR8Vnv7m9xOBTPl9v8OGrSsdNFUu5VoWiOlq7ZUMxO/m3Zxw8/cy/3dJG3EM9I9hihhL+PGpAAcEqSgHFoVuX5zNgo/SHfjp77Gv84xojt+nOmfhcRfsXH/CQP3VBj274e/kMbDSZz/kKp/USgezhOt8n//45d39998BuPOF7RVe3tNvAyaTI4jmmqamxaytFChnO87yvMSl0vzOn/xhIU9SKEeHARy3i+KF+UrpXnxNvi9TEltQAfbnSJBpFXubgayrAKeiifWqZQZfQjBOunVKzSuY7FgoRH0j0YcvSvUr0iq0aPbP52ds0uzzYJ7fMer1SDe/Tw4sgwq957oLMtDlFHy2m9F/NQmrVSumpOlXq/e++Faa1ZN3fpVyS1gHuGg25Ocz6W15IyhAZy1eatY8FgTu7u6fQjvSttbprR4KcVc59Z046TY1lNs0rG8XpbXIOHvwaLeAxzFhH5RlRDt4E4z/3bV+nQ8OGpeO3aL8z5Hew48X+jf7sd3raTf3gXZAex65C1MZVymcqQaUPAkYwCdUvA8DbEirSunqLeQ4xy5VeduXZ3t6onjBvZa7bKHkWJNs4Kh9b2Cg7nu2Blr996v+fN0/++6j2qvGnwQ5W8XISKZKV4+FbMpa5n0unHL13v8A9nH57rrcYJXzmaM+S1ujWdq4Dcn2RWKYQInTqbHQumSurwNu+e/5ztzvv8as/MKMTNnlnU0yH5nS7jN1PosN0Zmzj7oK2/s7c2hQCQkeMBdln/8Fn+LQ3nXldqfGa1uFvlczyCXa9/0TQ8oHn7y3x1QxdGiZfmYxj9bHTfIafIEVA95VW+Z3sLL9j8Ln1+li4xXYQeKLv1+jiT/5Sr/Hrm1pF43CkOtVhRwg070+fT42qWtwtPs8PN/3zZYql2egjdNfqu1K8ajfDyvmPoc2pmyd/6bP3VMlFKwc7rokIK14dt47ZBwTsf/+SJhuP70ma/HrWx+WNpXnbfcLupayu3AIoFSMQrRn3gxgIe1+25uK1+d/4Erv8Xp3+4vXm8ZOKrfHvSHUUp/M8FKLg+AE9nZ1MABPAYAAAAAAAALjUAAAMAAABxhstQEv/////+//////90w8LBwNrT1j40+1L/T1gIWsFdj2o/+f87bQooiU1iz8vx1TyeGMfX46F8Gp9ffnx+fb4m7bWe3nQ8gtda6OS4erizZNel9n2n1nmP9YiU/MqUgcSRRo1c8pr3Qap7dCxxkMUb24fIfDk3sXat0f9sWLxL9Pxr+rjo+klnTfIQtKiT9ietLbdboyi+4Mg5HnU3Kc583Krvx9gs7TofDYpOyfl9Po2n60MONIsdDI8g13u9Fua7UHr1ncg4EGaYajvnEZEpOazRaDkfn05RhIR2o0mvCieDGsF832tRfEXdVvR0lHXqytq5VG00g5r158reLU52nJd2ExLAa27Xmeau38d8XyPkuabbtZL3rPWsd3VqTx35UrtGeHL7rEcSDbkuNZw6TaFdWfmaMsevE3/yr8gwnUpAISm7aEr91iPkAJJT2snGIQkikX6FPjmTNeqSIUdGFrVqAlVmzSZPO4eEo5yKVKLTxVWufj8NeP/6/U4QB+h4ajZKrThztDRHralfoSOyIafZAWikIZyawLTkb4ltq//Jb8wdMQkVoYVouXR+iEpOTgJHMEfSsVZgDxD9oDZRmyTbmUm0dgWAq+J8pqPESgsKGUdOxdw0TtA1Yh3JA334+vnUQv/pJ64wZUrSTKGcgFaowpEOCdF5JCK3Q8DFKNEtQ8rcLdnkUzd5VtO0LhWdDiIU3QDhwqhJAISlQC/rLCDr5/oIahhjtjcWtCtLs0P+NTB8fQxKS03ymupDa93RUUFgPz02V6cnKaUx5ejt1nEuwZQFxP1GinnnCqrC5K83dfk/NaR7b9zPiVWUj3Odb+XZvd4VjXu2QWfudnI62hEuPaoxb+48FPDLbKqmWUj0KDP25meS7QeES3sWpItn6r3Ndt/Blj++IRcfnPP0Rir+3HBu/lmULVLQXFmQbqitaT6V92UIVSzJ+qmm2nKjqbT/K/nvGO3/wM8wjX0exV/K3OX6JmLxH81xefub0gHuwafNGv7u3v/z3sP0+W0843vwEWx/fpzoRwWT956pmUxb3CoPX3ev781+8HvsaanUpeh1OJVGuVe+cOhj1AreRP16XqHWTC0hWISXNtt5R5sU11D/mvON+xYve6z5zGe1Bi+fOrVkbt+avjv0q4Q+ztVEstCodGLqKZrlpendj4UPdytf3cLyoNWP+CVxbfgW5xUhuD96xx09dbfSvyWP1dvNEX3wKXOxyBF6wrZ42UOc/6q8KezHts2jUb6wuX571dUaAXkCIQeXttdoru6zbr5mVuvR9Bq5ajqtNtV1hadZK+Ud128vjzpPt6qdhPqm6F+z9hxUXxssw1p+e7VYmXMXmpRb7cW/Wr09RKE/fiLK0CuzEun40yqvye/NHW95uohnNvQ1suPUdizcoOuX6/BKeXWPeknxasrY5aeMdTrb+UX/261CjOmJubXwr0NodQqRiP3CQ57qwbMdNhPaaq0VpPP9ngXFJ0F2qf447/nNosM/qBAyNSJV3+go9vcqvuvksGI7emtjV23/uZWjZg9HNHHS/PJMg2RkTWkcBDwmpyw/IF6Sg/kZfqvlGvVM1JHV4vepPflWlpmspp0h2aHmY9mP+B2rcNP1174i8iOubaFC0Rtbw+TobD3L/8Z+Uu5UVqk0GYZN6uKUubwv1xHlPbs3u5jg0LxFXUiBX/D5rR7l021DXsn0zsWgVyjlp7Qtj0vTKCd4aBQAljN7kf/M+Qg4YN6Zbbryv9N+QpEa7npz2IGZlDNRR9/x5Py/eDE7FbLw5re4fR3eljc3Lx73/fL5epXzf8WHz/vZyLY+qPc8Otu7Pp/++vv5vKXl8/76b//99x+X8TF9/vB/peYybaHHq//5H79Y+/ffhmXW337Lrbo8j9+3XF3M//++UZa/p3Tu2fp+7XH/T88ti4nXR19T+oz4+mzPNV1rt90Ws9vH+f2vXT1UHd3n+dpH+lvLP+b3Zx/91sNIwPn8/WP48cl8GLbfpP/2vv3w9C/PKy315yOf/4rPs2t4+vYybL+f1nPq2le8qrul3l4q067lVD0d4/a6lPr4YKlSY/hKnP04uM9H6Dzr/I79lkY967G6knKFfFcfn/Zqq20aSfSXveprUH3054tj6XPQnpyaa2XJgnkCqr47+9VlVhF1VnjtRwUaJyWp36as+tHhyLocKXOlCs+nS7VSuyfRoD+GvebJPMiRtUoy36vrPg76ahFxvnfMrMF87Ece1CKPFufGdgInV/f4pJac0LXW1rmFo6UDQG6cJE/XCm9lUX3vUWOvPw/Tcnx015+HX05L6pEOASE4rY8slsWo87Pv5dLqTJXUQaZudKmJ+5Cn0bwe+uO3g9UPIQoh6L2SHVVakpzJqqJSX1OCPkKj5852UklnJ6SYs3ZxvAOtgkMhDa9zT40i1ppVqsoRj1OnaKLSoSjiQK091ZpKJ7tAZo0ZrU53a+My+ca3maIiR2eCZ0j0pp6sCD3qZ8ig9XsmTO37uEoNAEiGxIkCV7H0uNDsLSde9j/GZn8B129e1vCwSbvKqIaCq5hAK/+5Try/61VllnXeCRduekEnJrcZsLoJfPIit0YNOL+Sbncnaky/6Ozt0Z01yEjfddROZBcy+p5F/yohkj7wfU0yCfIl58+zJ/qgFCGy5XLK4rNQW3RcyUofacJqeQQXyUVVdD0X7EAa97tl7fsh0PZMM320ZrAmppXujzy7xGs3Ba/YMct4P4u9GjqJ3kxEXh2YGPfDmym5Wsghk3b9EhdkorHL6D9Ob4N1OL6j6c5U0j12F6ymknLE7X8PgW4TzLH7CUD4Ge7pVV+HZy/uH65xxN+uE9stTVXC9pJnC13EqbmhuSqdoggWies8oZmJRmyVsHPfZsnOgvRcu7M/obEmxnND8t6l6649oDMDxMze2/IPGULiaWVvPv/ZtSPNbrXL8Dmj/jwexp6M+/OJuOPTkQP8w/E39xOfP16DmRfMZRrb6j7/IZHQalVzw3mtUTdU1VL3syP8lp4MWwNB4zc0n6lM6kCpNT3pxPP5sKKQG7xzurnXW/fmGXRXMJzEOE/hyHxjLBr0ykRs71Oa3jXwBF4wWQrIyDD1fn+39qnrHsHN5mEBjuZIeP40iOMn7Y8vcW5t5r2TFOpk/U9Fo663QMUMCc4esZWGftNhZvuO/BN1/XnSnfb7lU71K7J/0PZckvc9ZfBZn+Jj0piQ5NfBcpMnopTfs9Lx7SVOG/MX7ZzNMU0zhKDf/1X0rGPfqe7i2rLngNDVLCKfUhtb97TTSqK6Hn0AVoQzl3WQh2tIgmw8+BGrh2zlAlQbdFpsFBxMsD8k8TPcUlF5N+VV08F09GepyQdr3DizVjbOG6yMVLvysnekqigl67E/iajTVcVvLyj6tfyJT4XjsKel0ZYqkUXaW+HlXSMd6W6F9dpT+MnBG8c/bD5NauZs6OuYxrr6LXY815t4jXmVa47ah8pX2EJi71nsOd6rO2PmQWRRK9O7VX14bK9DrF0b/+E9ZVH9sRZ8vG7jiH0OxiwGVDt9s+c3DibRsZeQTT/46oJ5T7QvjxSwthlrkSMgPpSqbIlj/AKEvUp+uVBXnxi0r1f5XzJuaUC07QDvL/LvM/33Mde3u8yM6JbL+pm3F9Ezbr2b/uTIN70XdWvtDM2I6zrO8LTI1xJ9BlV3ryWbnDsMAyALvHluV9gQz+kO390f6hd8yRgq/nQbTm1gyFHNstVdPFqaVQ1fH4871TirsKxq9ZRd0+jJJkebuOb+tHCs93e+Q8wwMq1OyPfJr5J8DsJxETXH/YXi8VDjHN21FLoI6ZUbgS0ct9Xx6Pa/uVuvP9tXNeWhOwZkvXb8ctscxmyCCXvt/Mdls6WZpPX86Wo8iZvH9uWzES+KjQdQnw/VFFl6uPEdP3NjovMmWbQfN1XzNxERy7R+i8MheZAaclyOLCQB6xFdpZK9E0mYSEAOFvEdhhpkLymSqYvJYez+5fb1Lo4eG53l8YuIbq+n9/RLCBYe3z6OJVx9w4KkqXSLB1pVsZBCf34/GCEa229XWvvLQsZYHnXHDP7qQXGfbl7tPqX5tP7yQ7bOkDdBiyYmF3HhHAII/pSbAyS9Xv2tiupdE6gD6nJd+SvLSz4Bps/Pfpt/ffwiv+pmP8R9lHtUYzIeGvmsLzePz+vWulfOdXZeL7Iu5iOShaxc75g75fT38PLLPxpZ5R6Fc4gy52cfeei0XpBuFFSxYVHjyt3C1TEn3y3vY+R4RzM5WmHZ6OjTaHZ7nqy2qvQblUa/hafEgTrSlj7QmXhyqCIUdz2sejonwEKf15Zlo6lo3+fDLnGOUEZYyN70DccRbZVKo5YfP63HtwFJ2/wLVwlEva788ofIK13Utl67fpmp6qtCbPu99u738ibCfsTLh/nO5/ptmuTBMshgzLfeN5qvKbpW74myPlsnJs3ZaN3npPZy/dzevaozRBzCISXaugf1E4xU3RQujJh4Ur25Jlq4OfuY28eNn4xF08DGcBcpvKaVqCz33I7G73hWrtWYh4wmhLAPxLReYVu4L7hnzu2WtwiCx1m7dur+EmQXffybPe9SsS/xMXZx81eVtV/qtO//N8hvPeGfz5cZryc9xwo8wUoeKupXD8T+Fqzs20zZqrWhmhrvPX4/v/r457rVVw6jfXv8Ky1H/sfrc/2vf7qfu/vG7ma/X//q93f9as6PrMkyf5p/sITTj2XK7h+PIcV5Pl1o39LyfKveU7zjLCbtlXvUId3hkPmUo3qf5Ek7LWmSZc6hBnJjl/E2q2mzStdfe1+J3e/gDo2XanLTFVcw7m91il6f/hzjC+XwCvr/93v+Dh+vht3VWU33NEfv5Bgji7yv8QkqG3RXnpLZo6sZq69DkN3zG10br5aqa7JTypP62OdszGPHBjzFil8crRkqDI9gu76pnN7eaz6vcddXx7Tz47s+yDfmgz7f2LBM54fn42M3D6/7/Lw//f++/cX97YzH7W8vFV6+705Mfd4kXVWH8fc8d76IJrMbfdThKcd5DOf84BdzRdy0bMdn7sB5pNGaQ9XeCGOZp2wnju0M/qKCGIRUJrCh/yqoio3hZ7lgjSP+XE+4fb6kKqqasBwkcar4wfvvvOeE22/aU7KLSe6GbcGj/xz3Pp2Jt66iUwOzubxr0C9+M20uxup+uizuywFWbj8BJj+ebgB0zMruPn56rBhn8SMDs+yH9wteNfbHP//0/m6WEeWI/eUu/Pr4tDXmzZmnF9+/vR5H++ut+Xr6l8/e8/T48nWprz+t/f52X13PTWKN+vnUVtdztSt9bY34P3Ies1w/fm5ZLUMTs7WjNbICQaOBpUY536i7uenXxneepmUQ/EfY+dKmMSDRGeyjcu5YAU9akQXJCuc4JxX2yjolS5rn7tNUJruXmVnA/LQ9revicNS1M0xzW6wBvenmHqz0nqag2/Bp1d1DC/xSYFylprRVOjdT74cjAQAA";

    public static function writeSoundToFile(path:String):Void {
        var bytes = Base64.decode(base64Data);
        File.saveBytes(path, bytes);
    }
}
